name: Release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: set_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::${latest_tag}"

      - name: Release
        run: gh release create "${{ steps.set_tag.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
